name: Build Main
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-matrix-8-25-coveralls-main.yml@main
    secrets: inherit
