name: Build Release
permissions:
  contents: read
on:
  release:
    branches:
      - main
    types: [released]

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-matrix-8-25-coveralls-release.yml@main
    secrets: inherit
