name: Build Pull Request
permissions:
  contents: read
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-matrix-8-25-coveralls-pr.yml@main
    secrets: inherit
